home/urls.py
from django.contrib import admin
from django.urls import path

from home import views
urlpatterns = [
    path('',views.index,name='index'),
    path('index/',views.index,name='index'),
    path('about/',views.about,name='about'),
    path('contact/',views.contact,name='contact'),
    path('services/',views.services,name='services'),
    path('details/<int:id>',views.details,name='details'),
    path('order_data/<int:id>',views.view_order,name='view_order'),
    path('myorders/',views.myorders,name='myorders'),


    #path('kulfi_details/<int:id>',views.kulfi_details,name='kulfi_details'),

    #path('<str:model_name>/<int:pk>/', views.product_detail, name='product_detail'),
    path('cart/',views.cart,name='cart'),
    #path('cone/',views.cone,name='cone'),
    #path('bar/',views.bar,name='bar'),
    path('signuppage/',views.signuppage,name='signuppage'),
    path('login/',views.loginpage,name='login'),
    path('logout/',views.logoutpage,name='logout'),
    path('add_to_cart',views.add_to_cart,name='add_to_cart'),
    #path('add_to_cart_kulfi',views.add_to_cart_kulfi,name='add_to_cart_kulfi'),

    path('remove_item/<int:id>',views.remove_item,name='remove_item'),
    path('place_order/<int:id>',views.place_order,name='place_order'),



        



    ]

shopping/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.db import models

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=120)
    email = models.EmailField()
    phone = models.IntegerField()
    desc = models.CharField(max_length=300)
    date = models.DateTimeField()

    def __str__(self):
        return self.name
    
class Product(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=300)
    disc = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='media/')
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name 

   
    
    def save(self, *args, **kwargs):
        # Automatically generate the slug based on the title
        self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    






    
    
class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=1)
    image = models.ImageField(upload_to='media/')
    quantity = models.PositiveBigIntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} x {self.product.name}"

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='orders')  # Correct the ForeignKey reference
    order_date = models.DateTimeField(auto_now_add=True)
    address = models.CharField(max_length=400)
    pincode = models.IntegerField()
    total = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"Order for {self.product.name} by {self.user.username}"



class CustomerProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=20)

    def __str__(self):
       return self.user

home/views.py
from django.shortcuts import render,HttpResponse,redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView
from datetime import datetime 
from home.models import Contact
from home.models import Cart,Product,Order
from django.shortcuts import render, get_object_or_404
from django.views import View


# Create your views here.
#@login_required(login_url='login')
def index(request):
    return render(request,'index.html')

#@login_required(login_url='login')
def about(request):
    return render(request,'about.html')


#@login_required(login_url='login')
def contact(request):
    if request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        desc = request.POST.get('desc')
        contact =Contact(name=name, email=email, phone=phone, desc=desc, date=datetime.today())
        contact.save()
    return render(request,'contact.html')

def signuppage(request):
    if request.method == 'POST':
        uname = request.POST.get('username')
        email = request.POST.get('email')
        pass1 = request.POST.get('password1')
        pass2 = request.POST.get('password2')
        if pass1!=pass2:
            return HttpResponse("Your Password1  and password2 are not same.")
        else:
            my_user = User.objects.create_user(uname,email,pass1)
            my_user.save()
            return redirect('login')
    return render(request, 'signuppage.html')

def loginpage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password1= request.POST.get('password1')
        print(username,password1)
        user=authenticate(request,username=username,password=password1)
        
        if user is not None:
            login(request,user)
            return redirect('index')
        else:
            print(username,password1)
            return HttpResponse("Password is incorrect")
        
    return render(request,'login.html')

def logoutpage(request):
    logout(request)
    return redirect('login')


@login_required(login_url='login')

def services(request):
    service_data = Product.objects.all()
    data ={
            'service_data':service_data
        }
    return render(request,"services.html",data)


   



def details(request,id):
    
    details_data= get_object_or_404(Product,id=id)
    return render(request, "details.html" ,{'details_data':details_data})

def cart(request):
    cart = Cart.objects.filter(user=request.user)
    return render(request, 'cart.html', {'cart': cart})


    

def add_to_cart(request):
    user = request.user
    prod_id = request.GET.get('id')
    product_name = Product.objects.get(id=prod_id)
    product = Product.objects.filter(pk=prod_id)
    for p in product:
        image = p.image
        price = p.price
    Cart(user = user,product=product_name,image=image,price=price).save()
    return redirect('services')



       


def remove_item(request,id):
    cart_item = Cart.objects.get(id=id,user=request.user)
    cart_item.delete()
    return redirect('cart')



def place_order(request,id):
    if request.method == 'POST':
        address = request.POST.get("address")
        pincode = request.POST.get("pincode")
        user = request.user

        # Assuming you have a Cart model with a 'product' field
        
        cart_item = Cart.objects.get(id=id)
        order = Order(user=user, address=address, pincode=pincode, product=cart_item.product, total=cart_item.price)
        order.save()
        cart_item.delete()  # Remove the cart item after creating the order
        return redirect('services')
        
    else:
        # Handle cases where the request method is not POST
        # You might want to display an error message or redirect to an error page

       # user = request.user
        #prod_id = request.GET.get('id')
        #product_name = Cart.objects.get(id=prod_id)
       # product = Cart.objects.filter(id=prod_id)
       # for p in product:
       #     price = p.price
       # Order(user = user,product=product_name,total=price).save()
        return redirect('services')

def view_order(request,id):
    
    order_data= get_object_or_404(Cart,id=id)
    return render(request, "view_order.html" ,{'order_data':order_data})

def myorders(request):
    data = Order.objects.filter(user=request.user)
    return render(request,'myorders.html',{'data':data})


       

templates/about.html
{% extends "base.html" %}
{% load static %}
{% block body%}
<div class="container col-xxl-8 py-5">
    <div class="row flex-lg-row-reverse align-items-center  py-5">
      <div class="col-10 col-sm-8 col-lg-6">
        <img src="{% static '2.jpg' %}" class="d-block mx-lg-auto img-fluid" loading="lazy" width="700" height="500">
      </div>
      <div class="col-lg-6">
        <h1 class="display-5 fw-bold text-body-emphasis lh-1 mb-3">About Us</h1>
        <p class="lead">Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most popular front-end open source toolkit, featuring Sass variables and mixins, responsive grid system, extensive prebuilt components, and powerful JavaScript plugins.</p>
      </div>
    </div>
</div>
 {% endblock body %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title> {% block title %} {% endblock title %}index</title>
  </head>
  <body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="/index"></a>Ice-Creame</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/index">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="/about">About Us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="/services" tabindex="-1" aria-disabled="true">Products</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link active" href="/contact" tabindex="-1" aria-disabled="true">Contact Us</a>
              </li>
            </ul>
            <form class="d-flex">
              {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link active text-white" class="btn btn-primary" aria-current="page" href="">{{user}}</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active text-white" class="btn btn-primary" aria-current="page" href="{% url 'myorders' %}">Buying Products</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link active text-white" class="btn btn-primary" aria-current="page" href="{% url 'cart' %}"> <i class="fa fa-shopping-cart"></i>Cart</a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'logout' %}" class="btn btn-primary mx-2">Logout</a>
                </li>
                {% endif %}
                <li class="nav-item">
                  <a class="btn btn-primary mx-2" href="/signuppage">Sign Up</a>
                </li>
                <li class="nav-item">
                  <a class="btn btn-primary mx-2" href="/login" class="btn btn-primary">Sign In</a>
                </li>
               
                
                
            </form>
          </div>
        </div>
      </nav>
<div class="">
  {% block body %} {% endblock %}
</div>


<!--div class="bg-dark" style="margin-bottom: 0;">
  <footer class="py-2">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-1 text-white ">Home</a></li>      
      <li class="nav-item"><a href="/about" class="nav-link px-1 text-white">About</a></li>
      <li class="nav-item"><a href="/services" class="nav-link px-1 text-white">Product</a></li>
      <li class="nav-item"><a href="/contact" class="nav-link px-1 text-white">Contact</a></li>


    </ul>
    <p class="text-center text-white">© 2023 Company, Inc</p>
  </footer>
</div-->
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/cart.html
{% extends 'base.html' %}

{% block body %}


<div class="container col-xxl-8 px-4 py-5">
    
    <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
      <h1>Shopping Cart</h1>
      <hr>
      {% for i in user.cart_set.all %}
          
          <div class="col-10 col-sm-8 col-lg-6">
          
              <h6 class="display-5 fw-bold text-body-emphasis lh-1 mb-3">{{ i.product}}</h6>
              <p>Price : {{ i.price }}</p>
              <p>Quantity : {{ i.quantity }}</p>
              <a type="submit" class="btn btn-primary" href="{% url 'remove_item' i.id %}">Remove</a>
              <a type="submit" class="btn btn-primary" href="{% url 'view_order' i.id %}">Order</a>

              



          </div>      
          <div class="col-10 col-sm-8 col-lg-6">
            <img data-zoom-image="/media/{{ i.image }}" src="/media/{{i.image }}" width="200" height="150">

          </div>
          
          <hr>
      {% endfor %}
    </div>
</div>
 {% endblock body %}

templates/contact.html
{% extends "base.html" %}

{% block body %}
<!--div class="container-fluid px-0 mb-3"></div>
<img src="https://source.unsplash.com/1200x400/?phone,contact" class="d-block w-100 mx-0" alt="...">
<h1 class="text-center">Contact Us</h1>
</div-->

<div class="container mb-3 py-4 mt-5">
  <h2>Contact Us</h2>
<form method="POST" action="/contact">
    {% csrf_token %}
    
    <div class="form-group mb-3">
      <label for="exampleInputname1" class="form-label">Name</label>
      <input type="text" class="form-control" id="name" name="name" aria-describedby="name" placeholder="Enter your Name">
      
    </div>
    <div class="form-group mb-3">
        <label for="exampleInputname1" class="form-label">Email</label>
        <input type="email" class="form-control" id="email" name="email" aria-describedby="email" placeholder="Enter your Email">
        
    </div>
    <div class="form-group mb-3">
        <label for="phone" class="form-label">Phone Number</label>
        <input type="text" class="form-control" id="phone" name="phone" placeholder="Enter your Phone Number" >
    </div>
    <div class="form-group mb-3">
        <label for="desc" class="form-label">Tell me about what you want to contact me for...</label>
        <input type="text" class="form-control" id="desc" name="desc" placeholder="Enter something" >
    </div>
    <button type="submit" class="btn btn-primary ">Submit</button>
  </form>
</div>
 {% endblock body %}

templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block body %}


<div class="container col-xxl-8 px-4 py-5">
    
  <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
      <div class="col-10 col-sm-8 col-lg-6">
        
     
        <img data-zoom-image="/media/{{ details_data.image }}" src="/media/{{details_data.image }}" width="500" height="500">
       
      </div>
      <div class="col-lg-6">
        <h6 class="display-5 fw-bold text-body-emphasis lh-1 mb-3">{{ details_data.name}}</h6>
        <p class="lead">{{ details_data.disc }}</p>
        <p>Price : {{ details_data.price }}</p>
        
        <form action="/add_to_cart">
          {% csrf_token %}
          
          <input type="text" value="{{ details_data.id }}" id="id" name="id" >
          <button class="btn btn-primary btn-sm" type="submit">ADD TO CART</button>

        </form>
      </div>
  </div>
</div>
 {% endblock body %}

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block body%}
<!--carousel code-->
<div class="container-fluid">
    <div id="carouselExampleIndicators" class="carousel carousel-dark slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
          <div class="carousel-item active">
           <img src="{% static '2.jpg' %}" class="d-block w-100" alt="..." style="height: 600px ;">
           <div class="carousel-caption d-none d-md-block">
            <h1>The Most Delicious Place On The Internet!</h1>
            <p>Some representative aceholder content for the first slideThere's so much to explore, here at the home of ice cream.</p>
          </div>
          </div>
          <div class="carousel-item">
            <img src="{% static 'ishan-seefromthesky-NhJX41giJFs-unsplash.jpg' %}" class="d-block w-100" alt="..."  style="height: 600px ;">
            <div class="carousel-caption d-none d-md-block ">
              <h1>The most delicious place on the Internet!</h1>
              <p>Some representative placeholder content for the first slideThere's so much to explore, here at the home of ice cream.</p>
            </div>
          </div>
          <div class="carousel-item">
            <img src="{% static 'phil-hearing-B_pEC0rSb7o-unsplash.jpg' %}" class="d-block w-100" alt="..."  style="height: 600px ;">
            <div class="carousel-caption d-none d-md-block text-white">
              <h1>The most delicious place on the Internet!</h1>
              <p>Some representative placeholder content for the first slideThere's so much to explore, here at the home of ice cream.</p>
            </div>
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
</div>

<!--cart start-->
<div class="container">
  <div class="mt-4 py-3">
    <h2 class="text-center fw-bold">Our Best Selling Products</h2>
  </div>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <div class="col">
      <div class="card">
        <img src="{% static 'brenda-godinez-AAHdL8gp5b8-unsplash.jpg' %}" class="card-img-top" alt="..." style="height: 300px;">
        <div class="card-body">
          <h5 class="card-title">Chocolate</h5>
          <p class="card-text">An ice cream loaded with a heavenly Chocolate</p>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card">
        <img src="{% static 'flavio-shibata-z_eoi3ppf5U-unsplash.jpg' %}" class="card-img-top" alt="..." style="height: 300px;">
        <div class="card-body">
          <h5 class="card-title">Malai</h5>
          <p class="card-text">India’s most loved sweetmeat in its creamiest and tastiest avatar.</p>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card">
        <img src="{% static 'spork-n-fork-aWBweuWlju4-unsplash.jpg' %}" class="card-img-top" alt="..." style="height: 300px;">
        <div class="card-body">
          <h5 class="card-title">Ladoo Ice-Creame</h5>
          <p class="card-text">A desi sweet you can never say no to, loaded with Motichoor Ladoo</p>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card">
        <img src="{% static 'kelsey-curtis-G5ZenftPPOA-unsplash.jpg' %}" class="card-img-top" alt="..." style="height: 300px;">
        <div class="card-body">
          <h5 class="card-title">Gulab Jamun</h5>
          <p class="card-text">India’s most loved dessert in a creamier avatar.</p>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card">
        <img src="{% static '2.jpg' %}" class="card-img-top" alt="..." style="height: 300px;">
        <div class="card-body">
          <h5 class="card-title">Pista</h5>
          <p class="card-text">India’s most loved  a creamier avatar.</p>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card">
        <img src="{% static '3.jpg' %}" class="card-img-top" alt="..." style="height: 300px;">
        <div class="card-body">
          <h5 class="card-title">banana</h5>
          <p class="card-text">An ice cream loaded with a heavenly Banana Ice-Creame.</p>
        </div>
      </div>
    </div>
  </div>
</div>

 {% endblock body %}

templates/kulfi.html
{% extends "base.html" %}
{% load static %}


{% block body %}
<div class="container-fluid">
  <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'images/2.jpg' %}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h1 class="text-white">All Ice-Creame flavors</h1>
          
        </div>
      </div>
    </div>
  </div>
  <div class="container my-5">
      <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for i in kulfi_data %}
        <div class="col">
          <div class="card h-100">
           <a href="{% url 'kulfi_details' i.id  %}"><img src="/media/{{ i.image }}" class="card-img-top" alt="..." height="300" width="100"></a>
            <div class="card-body">
              <b>{{i.name}}</b>     
              <div class="d-flex justify-content-between align-items-center">
                <small> Price:{{ i.price}}</small>
                
              </div>         
              
            </div>
            
          </div>
        </div>
        {% endfor %}
      </div>
       
        
      </div>
      
      
  </div>
</div>
 {% endblock %}

templates/login.html
{% extends "base.html" %}
{% block body %}

<div class=" container mt-5 mb-3 py-4">
  <h2>Log In</h2>
  <form action="" method="POST">
    {% csrf_token %}
    <div class="form-group mb-3">
      <label for="Name" class="form-label">Name</label>
      <input type="text" class="form-control" id="username" name="username" aria-describedby="username" placeholder="Enter your UserName">
      
    </div>
    <div class="form-group mb-3">
      <label for="Password" class="form-label">Password</label>
      <input type="password" class="form-control" id="password1" name="password1" aria-describedby="password1" placeholder="Enter your password">
      
    </div>
    <a href="{% url 'signuppage' %}">Register</a>

    <button type="submit">Login</button>
  </form> 
</div>


{% endblock body %}

templates/myorders.html
{% extends 'base.html' %}

{% block body %}
<h1>Buying products</h1>
<table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Name</th>
        <th scope="col">Address</th>
        <th scope="col">Date</th>
        <th scope="col">Pincode</th>
        <th scope="col">Price</th>

      </tr>
    </thead>
    <tbody>
    {% for i in user.order_set.all %}
      <tr>
        <th scope="row">{{ i.id }}</th>
        <td>{{ i.product.name }}</td>
        <td>{{ i.address }}</td>
        <td>{{ i.order_date }}</td>

        <td>{{ i.pincode }}</td>
        <td>{{ i.total }}</td>


      </tr>
    {% endfor %}
    </tbody>
  </table>


{% endblock body %}

templates/services.html
{% extends "base.html" %}
{% load static %}


{% block body %}
<div class="container-fluid">
  <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'images/2.jpg' %}" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h1 class="text-white">All Ice-Creame flavors</h1>
          
        </div>
      </div>
    </div>
  </div>
  <div class="container my-5">
      <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for i in service_data %}
        <div class="col">
          <div class="card h-100">
           <a href="{% url 'details' i.id  %}"><img src="/media/{{ i.image }}" class="card-img-top" alt="..." height="300" width="100"></a>
            <div class="card-body">
              <b>{{i.name}}</b>     
              <div class="d-flex justify-content-between align-items-center">
                <small> Price:{{ i.price}}</small>
                
              </div>         
              
            </div>
            
          </div>
        </div>
        {% endfor %}
      </div>
       
        
      </div>
      
      
  </div>
</div>
 {% endblock %}

templates/signuppage.html
{% extends "base.html" %}
{% block body %}



<div class="container mt-5 mb-3 py-4">
   
    <form action="" method="post">
        {% csrf_token %}
  
        
        <div class="form-group mb-3">
            <label for="username" class="form-label">Username</label>
            <input type="text" class="form-control" id="username" name="username" aria-describedby="username" placeholder="Enter your Name">
            
        </div>
        <div class="form-group mb-3">
            <label for="email" class="form-label">Email</label>
            <input type="email" class="form-control" id="email" name="email" aria-describedby="email" placeholder="Enter your Email">
            
        </div>
        <div class="form-group mb-3">
          <label for="password1" class="form-label">Password1</label>
          <input type="password" class="form-control" name="password1" aria-describedby="password1" placeholder="Enter your Password1">
          
        </div>
        <div class="form-group mb-3">
            <label for="password2" class="form-label">Password2</label>
            <input type="password" class="form-control" name="password2" aria-describedby="password2" placeholder="Enter your Password2">
            
        </div>
        
       
        <button type="submit">Sign up</button>
       
    </form> 
    </div>
  


{% endblock body %}

templates/view_order.html
{% extends 'base.html' %}
{% load static %}
{% block body %}


<div class="container col-xxl-8 px-4 py-5">
    
  <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
      <div class="col-10 col-sm-8 col-lg-6">
        
     
        <img data-zoom-image="/media/{{ order_data.image }}" src="/media/{{order_data.image }}" width="500" height="500">
       
      </div>
      <div class="col-lg-6">
        <h6 class="display-5 fw-bold text-body-emphasis lh-1 mb-3">{{ order_data.product}}</h6>
        <p class="lead">{{ order_data.total }}</p>
        
        
        <form action="/place_order/{{ order_data.id }}" method="POST">
          {% csrf_token %}
          <input type="hidden" name="id" value="{{ order_data.id }}">
          <div class="form-group mb-3">
              <label for="address" class="form-label">Address</label>
              <input type="text" class="form-control" id="address" name="address" aria-describedby="address" placeholder="Enter your address">
          </div>
          <div class="form-group mb-3">
              <label for="pincode" class="form-label">Pincode</label>
              <input type="text" class="form-control" id="pincode" name="pincode" aria-describedby="pincode" placeholder="Enter your pincode">
          </div>
          <button class="btn btn-primary btn-sm" type="submit">Order</button>
      </form>
      
        
      </div>
  </div>
</div>
 {% endblock body %}